language: go
sudo: false
go:
  - 1.9.x

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev libnetfilter-queue-dev python3-pip
  - wget https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -O /tmp/protoc.zip
  - unzip -o /tmp/protoc.zip -d /tmp/protoc
  - export PATH=$PATH:/tmp/protoc/bin/
  - go get github.com/golang/protobuf/protoc-gen-go
  - go get -v github.com/Masterminds/glide

script:
  - make protocol
  - make deps
  - make daemon/opensnitchd
