language: go
sudo: false
go:
  - 1.9.x

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev libnetfilter-queue-dev
  - go get -v github.com/Masterminds/glide
  - make protocol
  - make deps

install:
  - make daemon/daemon

script:
  - sudo ./daemon/daemon -h
