[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "~1.1.14"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~1.11.2"

[prune]
  go-tests = true
  unused-packages = true
